### PR TITLE
feat: enable swarm-desktop with environment variable

### PR DESCRIPTION
**Pull request by vojtechsimetka**
Resolves https://github.com/ethersphere/js-team-zenhub/issues/135

### CODE REVIEW

**Comment by Cafe137** [comment]
How does this work? Is this picked up in all CI workflows?

**Comment by vojtechsimetka** [comment]
> How does this work? Is this picked up in all CI workflows?

Oh you are right. I tested this in a test repo but I guess I had something wrongly setup.  By default github actions don't load `.env` files. So our options are:

1. We use github action like [simple-dotenv](https://github.com/marketplace/actions/simple-dotenv) or [dotenv](https://github.com/marketplace/actions/dotenv-action)
2. We manually provide this variable to the workflows.

Which one do you prefer

**Review by AuHau — CHANGES_REQUESTED** [review]
So IMHO the right place to put this is directly to the workflows where Dashboard is built in [`assets.yml`](https://github.com/ethersphere/swarm-desktop/blob/master/.github/workflows/assets.yml#L24) and [`pre-release.yml`](https://github.com/ethersphere/swarm-desktop/blob/master/.github/workflows/pre-release.yml#L29)

**Comment by vojtechsimetka** [comment]
Would you keep `.env` file for local setup? If you want to build it locally because you are for example testing something.

**Pull request closed without merging**
